name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build the project
        run: npm run build

      - name: Configure Git
        run: |
          git config --global user.email "salud.jon@gmail.com"
          git config --global user.name "Jon Salud"

      - name: Increment version
        id: npm_version
        run: |
          NEW_VERSION=$(npm version patch)
          echo "New version: $NEW_VERSION"
          echo "new_version=$NEW_VERSION" >> $GITHUB_ENV

      # - name: Push version increment
      #   run: |
      #     git remote set-url origin https://jon-salud:${{ secrets.PAT }}@github.com/jon-salud/theatre-app.git
      #     git push origin main
      #   env:
      #     PAT: ${{ secrets.PAT }}

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: build # The folder the action should deploy.
